/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../app-example/components/Collapsible`; params?: Router.UnknownInputParams; } | { pathname: `/../app-example/components/ExternalLink`; params?: Router.UnknownInputParams; } | { pathname: `/../app-example/components/HapticTab`; params?: Router.UnknownInputParams; } | { pathname: `/../app-example/components/HelloWave`; params?: Router.UnknownInputParams; } | { pathname: `/../app-example/components/ui/IconSymbol.ios`; params?: Router.UnknownInputParams; } | { pathname: `/../app-example/app${'/(tabs)'}/explore` | `/../app-example/app/explore`; params?: Router.UnknownInputParams; } | { pathname: `/game`; params?: Router.UnknownInputParams; } | { pathname: `/video`; params?: Router.UnknownInputParams; } | { pathname: `/../app-example/constants/Colors`; params?: Router.UnknownInputParams; } | { pathname: `/../app-example/hooks/useColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../app-example/components/Collapsible`; params?: Router.UnknownOutputParams; } | { pathname: `/../app-example/components/ExternalLink`; params?: Router.UnknownOutputParams; } | { pathname: `/../app-example/components/HapticTab`; params?: Router.UnknownOutputParams; } | { pathname: `/../app-example/components/HelloWave`; params?: Router.UnknownOutputParams; } | { pathname: `/../app-example/components/ui/IconSymbol.ios`; params?: Router.UnknownOutputParams; } | { pathname: `/../app-example/app${'/(tabs)'}/explore` | `/../app-example/app/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/game`; params?: Router.UnknownOutputParams; } | { pathname: `/video`; params?: Router.UnknownOutputParams; } | { pathname: `/../app-example/constants/Colors`; params?: Router.UnknownOutputParams; } | { pathname: `/../app-example/hooks/useColorScheme`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../app-example/components/Collapsible${`?${string}` | `#${string}` | ''}` | `/../app-example/components/ExternalLink${`?${string}` | `#${string}` | ''}` | `/../app-example/components/HapticTab${`?${string}` | `#${string}` | ''}` | `/../app-example/components/HelloWave${`?${string}` | `#${string}` | ''}` | `/../app-example/components/ui/IconSymbol.ios${`?${string}` | `#${string}` | ''}` | `/../app-example/app${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/../app-example/app/explore${`?${string}` | `#${string}` | ''}` | `/game${`?${string}` | `#${string}` | ''}` | `/video${`?${string}` | `#${string}` | ''}` | `/../app-example/constants/Colors${`?${string}` | `#${string}` | ''}` | `/../app-example/hooks/useColorScheme${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../app-example/components/Collapsible`; params?: Router.UnknownInputParams; } | { pathname: `/../app-example/components/ExternalLink`; params?: Router.UnknownInputParams; } | { pathname: `/../app-example/components/HapticTab`; params?: Router.UnknownInputParams; } | { pathname: `/../app-example/components/HelloWave`; params?: Router.UnknownInputParams; } | { pathname: `/../app-example/components/ui/IconSymbol.ios`; params?: Router.UnknownInputParams; } | { pathname: `/../app-example/app${'/(tabs)'}/explore` | `/../app-example/app/explore`; params?: Router.UnknownInputParams; } | { pathname: `/game`; params?: Router.UnknownInputParams; } | { pathname: `/video`; params?: Router.UnknownInputParams; } | { pathname: `/../app-example/constants/Colors`; params?: Router.UnknownInputParams; } | { pathname: `/../app-example/hooks/useColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
